### ISSUE TITLE
Some questions about the experiments.

### ISSUE THREAD

**Issue by Lotus-95** [easonyang1996/CS-CO#1]
Thanks for you job. And I have some questions about the experiments:
1. In your paper, you train the linear classfier on CS-CO backbone with n = 100, 1000 and 10000 training samples. How if you train the linear classifer on the whole training set? Will it imporve more?
2. The fully superviesed baseline model of ResNet 18 is trained on stain separated data with two backbones and concatenated features, or just the raw data with ResNet 18 which has only a half of parameters of CS-CO backbones? We think the latter is a unfair comparison. Because our experiments on PCam shows that only with stain separated data and concatenated features could improve the acc from 0.85 to 0.89.
3. How your code can be running? Could you add some notes about experiments reproduction?

**Comment by easonyang1996** [comment]
Thanks for your interest!

1. We didn't train the linear classifier on the whole training set, since NCT-CRC is easy to be classified. I think maybe the performance will improve if you use the whole training set, but the difference of performance between methods will be small.
2. For the fully supervised baseline, indeed we just use the raw data with ResNet 18. We also do experiments with ResNet 50, however, the improvement is not significant. 
3. Sorry for the inconvenience, we will update README soon.

**Comment by easonyang1996** [comment]
Please refer the updated README for experiments reproduction!
